# Generated by Django 5.2.5 on 2026-07-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'items_id',
                'ordering': ('id',),
            },
        ),
    ]
