# Generated by Django 5.2.5 on 2025-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EXBOUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, unique=True)),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('token_expires_in', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'exbo_users',
                'ordering': ('user_id',),
            },
        ),
    ]
