# Generated by Django 5.2.5 on 2025-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exbouser',
            name='token_expires_in',
            field=models.IntegerField(null=True),
        ),
    ]
