# Generated by Django 5.2.5 on 2025-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('ru_name', models.CharField(db_index=True, max_length=255)),
                ('en_name', models.CharField(db_index=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('infoblocks', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ('en_name',),
            },
        ),
    ]
