# Generated by Django 5.2.5 on 2025-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tierlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('icon', models.URLField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('rarity', models.CharField(db_index=True, max_length=50)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('status_state', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.TextField(blank=True, null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ('name',),
            },
        ),
    ]
