# Generated by Django 5.2.5 on 2026-07-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_builds', '0001_initial'),
        ('items_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='items_id',
            field=models.ManyToManyField(related_name='builds', to='items_db.item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='tags',
            field=models.ManyToManyField(blank=True, to='items_builds.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='build',
            table='community_builds',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
